name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build, Test, Bench
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_versions: ["stable", "1.38.0"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Check out source code
        uses: actions/checkout@master

      - name: Install Rust
        run: |
          rustup toolchain install --no-self-update ${{ matrix.rust_versions }}
          rustup default stable

      - name: Build
        run: cargo build --features=hyper --verbose

      - name: Run tests
        run: |
          cargo test --features=hyper --verbose
          cargo bench
